import type { GatewayModelConfig, GatewayProviderConfig } from "./types";

export const chinaProviderIds = new Set(["deepseek", "qwen", "kimi", "zai", "siliconflow"]);

export const providerPresets: Record<string, GatewayProviderConfig> = {
  openai: {
    id: "openai",
    displayName: "OpenAI",
    kind: "openai-compatible",
    baseUrl: "https://api.openai.com/v1",
    apiKeyEnv: "OPENAI_API_KEY",
    enabled: true,
    regions: ["us"],
    jurisdiction: "us",
    dataPolicy: {
      allowTraining: false,
      allowLogging: false,
      zeroDataRetentionAvailable: false,
      byokOnly: true,
    },
  },
  openrouter: {
    id: "openrouter",
    displayName: "OpenRouter",
    kind: "openai-compatible",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyEnv: "OPENROUTER_API_KEY",
    enabled: true,
    regions: ["global"],
    dataPolicy: {
      allowTraining: false,
      allowLogging: true,
      zeroDataRetentionAvailable: false,
      byokOnly: true,
    },
  },
  google: {
    id: "google",
    displayName: "Google Gemini",
    kind: "google",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    apiKeyEnv: "GOOGLE_GENERATIVE_AI_API_KEY",
    enabled: true,
    regions: ["global"],
    dataPolicy: {
      allowTraining: true,
      allowLogging: true,
      zeroDataRetentionAvailable: false,
      byokOnly: true,
    },
  },
  deepseek: {
    id: "deepseek",
    displayName: "DeepSeek",
    kind: "openai-compatible",
    baseUrl: "https://api.deepseek.com",
    apiKeyEnv: "DEEPSEEK_API_KEY",
    enabled: true,
    regions: ["cn"],
    jurisdiction: "cn",
    dataPolicy: {
      allowTraining: false,
      allowLogging: true,
      zeroDataRetentionAvailable: false,
      byokOnly: true,
    },
  },
  qwen: {
    id: "qwen",
    displayName: "Qwen DashScope",
    kind: "openai-compatible",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    apiKeyEnv: "DASHSCOPE_API_KEY",
    enabled: true,
    regions: ["sg", "cn"],
    jurisdiction: "cn",
    dataPolicy: {
      allowTraining: false,
      allowLogging: true,
      zeroDataRetentionAvailable: false,
      byokOnly: true,
    },
  },
  kimi: {
    id: "kimi",
    displayName: "Kimi Moonshot",
    kind: "openai-compatible",
    baseUrl: "https://api.moonshot.ai/v1",
    apiKeyEnv: "MOONSHOT_API_KEY",
    enabled: true,
    regions: ["cn"],
    jurisdiction: "cn",
    dataPolicy: {
      allowTraining: false,
      allowLogging: true,
      zeroDataRetentionAvailable: false,
      byokOnly: true,
    },
  },
  zai: {
    id: "zai",
    displayName: "Z.AI GLM",
    kind: "openai-compatible",
    baseUrl: "https://api.z.ai/api/paas/v4",
    apiKeyEnv: "ZAI_API_KEY",
    enabled: true,
    regions: ["cn"],
    jurisdiction: "cn",
    dataPolicy: {
      allowTraining: false,
      allowLogging: true,
      zeroDataRetentionAvailable: false,
      byokOnly: true,
    },
  },
  siliconflow: {
    id: "siliconflow",
    displayName: "SiliconFlow",
    kind: "openai-compatible",
    baseUrl: "https://api.siliconflow.cn/v1",
    apiKeyEnv: "SILICONFLOW_API_KEY",
    enabled: true,
    regions: ["cn"],
    jurisdiction: "cn",
    dataPolicy: {
      allowTraining: false,
      allowLogging: true,
      zeroDataRetentionAvailable: false,
      byokOnly: true,
    },
  },
};

export const modelPresets: GatewayModelConfig[] = [
  {
    id: "openai/gpt-4.1-mini",
    providerId: "openai",
    providerModel: "gpt-4.1-mini",
    aliases: ["fast", "coding", "no-china-coding"],
    capabilities: ["chat", "streaming", "tools", "json"],
    contextWindow: 1_000_000,
    inputUsdPerMillionTokens: 0.4,
    outputUsdPerMillionTokens: 1.6,
  },
  {
    id: "openai/gpt-4o-mini",
    providerId: "openai",
    providerModel: "gpt-4o-mini",
    aliases: ["cheap", "fast"],
    capabilities: ["chat", "streaming", "tools", "json", "vision"],
    contextWindow: 128_000,
    inputUsdPerMillionTokens: 0.15,
    outputUsdPerMillionTokens: 0.6,
  },
  {
    id: "openrouter/openai/gpt-4.1-mini",
    providerId: "openrouter",
    providerModel: "openai/gpt-4.1-mini",
    aliases: ["fast", "coding"],
    capabilities: ["chat", "streaming", "tools", "json"],
    contextWindow: 1_000_000,
  },
  {
    id: "google/gemini-3.5-flash",
    providerId: "google",
    providerModel: "gemini-3.5-flash",
    aliases: ["gemini", "gemini-fast", "google-fast"],
    capabilities: ["chat", "streaming", "tools", "json"],
    contextWindow: 1_000_000,
  },
  {
    id: "deepseek/deepseek-v4-pro",
    providerId: "deepseek",
    providerModel: "deepseek-v4-pro",
    aliases: ["coding", "reasoning", "china-coding"],
    capabilities: ["chat", "streaming", "tools", "reasoning"],
    contextWindow: 64_000,
  },
  {
    id: "deepseek/deepseek-v4-flash",
    providerId: "deepseek",
    providerModel: "deepseek-v4-flash",
    aliases: ["fast", "cheap", "china-fast"],
    capabilities: ["chat", "streaming", "tools"],
    contextWindow: 64_000,
  },
  {
    id: "qwen/qwen3-coder-plus",
    providerId: "qwen",
    providerModel: "qwen3-coder-plus",
    aliases: ["coding", "china-coding"],
    capabilities: ["chat", "streaming", "tools"],
    contextWindow: 128_000,
  },
  {
    id: "qwen/qwen-plus",
    providerId: "qwen",
    providerModel: "qwen-plus",
    aliases: ["fast", "china-fast"],
    capabilities: ["chat", "streaming", "tools"],
    contextWindow: 128_000,
  },
  {
    id: "kimi/kimi-k2.7-code",
    providerId: "kimi",
    providerModel: "kimi-k2.7-code",
    aliases: ["coding", "china-coding"],
    capabilities: ["chat", "streaming", "tools", "reasoning"],
    contextWindow: 256_000,
  },
  {
    id: "kimi/kimi-k2.7-code-highspeed",
    providerId: "kimi",
    providerModel: "kimi-k2.7-code-highspeed",
    aliases: ["fast", "china-fast"],
    capabilities: ["chat", "streaming", "tools", "reasoning"],
    contextWindow: 256_000,
  },
  {
    id: "kimi/kimi-k2.6",
    providerId: "kimi",
    providerModel: "kimi-k2.6",
    aliases: ["coding-legacy", "china-coding-legacy"],
    capabilities: ["chat", "streaming", "tools"],
    contextWindow: 256_000,
  },
  {
    id: "zai/glm-5.1",
    providerId: "zai",
    providerModel: "glm-5.1",
    aliases: ["reasoning", "coding", "china-reasoning", "china-coding"],
    capabilities: ["chat", "streaming", "tools", "reasoning"],
    contextWindow: 1_000_000,
  },
  {
    id: "zai/glm-5",
    providerId: "zai",
    providerModel: "glm-5",
    aliases: ["reasoning", "china-reasoning"],
    capabilities: ["chat", "streaming", "tools", "reasoning"],
    contextWindow: 200_000,
  },
  {
    id: "zai/glm-4.5",
    providerId: "zai",
    providerModel: "glm-4.5",
    aliases: ["reasoning-legacy", "china-reasoning-legacy"],
    capabilities: ["chat", "streaming", "tools", "reasoning"],
    contextWindow: 128_000,
  },
  {
    id: "siliconflow/Pro/zai-org/GLM-4.7",
    providerId: "siliconflow",
    providerModel: "Pro/zai-org/GLM-4.7",
    aliases: ["reasoning", "china-reasoning"],
    capabilities: ["chat", "streaming", "reasoning"],
    contextWindow: 128_000,
  },
];

export function isChinaProvider(provider: GatewayProviderConfig): boolean {
  return chinaProviderIds.has(provider.id) || (provider.regions ?? []).includes("cn");
}
